apiVersion: v1
kind: PersistentVolume
metadata:
  name: arize-phoenix-db-pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/thedatapool/app-data/arize-phoenix/db-data
