#!/usr/bin/env bash
this_dir=$(cd $(dirname "$0"); pwd) # this script's directory
zot_dir=$(cd "$this_dir/.."; pwd) # apps/production/zot
repo_dir=$(cd "$this_dir/../../../.."; pwd) # repository directory

#-e: Exits immediately if any command returns a non-zero status (i.e., fails)
#-u: Treats unset variables as errors and exits immediately
#-o pipefail: If any command in a pipeline fails, the entire pipeline fails
set -eo pipefail

if ! command -v htpasswd >/dev/null 2>&1; then
  echo "Error: htpasswd not found (macOS ships one at /usr/sbin/htpasswd; on Linux install apache2-utils/httpd-tools)."
  exit 1
fi
if ! command -v gh >/dev/null 2>&1; then
  echo "Error: gh (GitHub CLI) not found - needed to push the passwords to consumer repos' secrets."
  exit 1
fi

# The plaintext passwords themselves - as opposed to the bcrypt hashes below,
# which is all zot ever sees - live only here and in 1Password. Written to
# disk (gitignored, matches the repo's ".env.secret*" convention) so a plain
# `onepassword-secrets.mts push` picks them up; previously they only ever hit
# the terminal once and were lost if not copied by hand.
plaintext_file="$zot_dir/.env.secret.zot-passwords"

# Regenerating both accounts (rather than one at a time) is simpler, at the
# cost of needing to re-`docker login`/re-push secrets everywhere even when
# only one account needed to change - acceptable since this is a small,
# internal set of consumers. "reuse" exists for re-running the rest of this
# script (rebuilding the hash file, re-pushing GitHub/1Password secrets)
# after a previous run's later step failed, without invalidating passwords
# that may already be partially deployed.
mode=rotate
if [[ -f "$plaintext_file" ]]; then
  echo "Existing plaintext passwords found at $plaintext_file"
  read -r -p "Rotate (generate new passwords) or reuse the existing ones? [rotate/reuse] " mode
  case "$mode" in
    rotate | reuse) ;;
    *)
      echo "Error: answer 'rotate' or 'reuse'."
      exit 1
      ;;
  esac
fi

if [[ "$mode" == "rotate" ]]; then
  ci_password=$(openssl rand -base64 24)
  mirror_password=$(openssl rand -base64 24)
  cat <<EOF > "$plaintext_file"
# Plaintext CI + mirror passwords for the zot OCI registry mirror auth.
# Generated by this directory's scripts/create-zot-htpasswd.sh, which also derives
# zot-htpasswd.encrypted (the bcrypt hashes zot actually authenticates
# against) FROM this file - the two are always in sync because one script
# run produces both.
#
# Gitignored; not committed. Back this up (or push a rotation) with:
#   ./scripts/onepassword-secrets.mts push --only zot
#
# To rotate both accounts, rerun this script and choose "rotate" - it
# regenerates both passwords and both files together, and re-pushes the
# GitHub secrets in every consumer repo. After rotating, re-\`docker login\`
# everywhere these creds are used (CI runner pods, kind clusters, local
# machines) that this script doesn't reach itself.
CI_PASSWORD="${ci_password}"
MIRROR_PASSWORD="${mirror_password}"
EOF
  chmod 600 "$plaintext_file"
else
  echo "Reusing existing plaintext passwords - not rotating."
fi

# Read back from the file rather than trusting the branch above, so the
# hashes and pushed secrets below are provably derived from what's on disk.
source "$plaintext_file"

tmpdir=$(mktemp -d)
trap 'rm -rf "$tmpdir"' EXIT

htpasswd_file="$tmpdir/htpasswd"
# htpasswd -n emits a trailing blank line after each entry on some platforms
# (confirmed on macOS) - filter those out so the file is exactly two
# "user:hash" lines with no blank lines in between. No comments here: zot's
# htpasswd parser expects strictly "user:hash" lines, so unlike the plaintext
# file above this one can't carry an explanatory header without risking a
# bogus user entry.
{
  htpasswd -nbB ci "$CI_PASSWORD"
  htpasswd -nbB mirror "$MIRROR_PASSWORD"
} | awk 'NF' > "$htpasswd_file"

# Encrypted as BINARY (not JSON/dotenv): the generator key "htpasswd" has no
# recognized extension, so Flux's kustomize-controller decrypts it via the
# binary format, which round-trips the raw multi-line file untouched - the
# JSON/dotenv sops formats can't represent multiple "user:hash" lines cleanly.
htpasswd_file_encrypted="$zot_dir/zot-htpasswd.encrypted"

# Prepare for sops (the include lives at repo root, not next to this script):
source "$repo_dir/scripts/_sops_config.include.sh"

sops -encrypt \
  --age "$age_key_public" \
  --input-type=binary \
  --output-type=binary "$htpasswd_file" > "$htpasswd_file_encrypted"

cat <<EOF
Wrote (both gitignored except the .encrypted one):
  ${plaintext_file}      (plaintext ci/mirror passwords - back up now)
  ${htpasswd_file_encrypted}  (bcrypt hashes, committed, consumed by Flux)

Back up the plaintext passwords to 1Password:
  ./scripts/onepassword-secrets.mts push --only zot

Sanity-check the htpasswd round-trip before committing:
  SOPS_AGE_KEY_FILE=$repo_dir/home-infra-private.agekey \\
    sops -d --input-type binary --output-type binary ${htpasswd_file_encrypted}
  # expect two lines: ci:\$2y\$...  and  mirror:\$2y\$...

To deploy, commit and push (the plaintext file is gitignored - only the
.encrypted one should ever be staged):

  git add apps/production/zot/zot-htpasswd.encrypted
  git commit -m "rotate zot htpasswd accounts"
  git push
EOF

# The repo list lives in scripts/actions-secrets.json, the single source of truth for
# which repos get which shared Actions secret; sync-actions-secrets.mts sets each one both as
# a plain Actions secret and with "--app dependabot" (see its header for why both).
# Repos are not discoverable from this repo, so that list is maintained by hand - add a repo
# the day it starts logging into zot in CI (grep its .github/workflows for "zot"/
# "oci-registry" to check). Known as of 2026-09-24: fernfiles and ramblefeed use the
# writable zot (ZOT_CI_PASSWORD) and the mirror; browser-chaperone, job-accelerator,
# tinkerbell and gpu-poet use only the mirror (ZOT_MIRROR_PASSWORD). gpu-poet-data does NOT
# use zot.
#
# The sync reads the values from the encrypted passwords file, so it is written first.
# It pushes straight to gh with the value on stdin, rather than printing commands to
# copy-paste, so the plaintext value only ever exists in this process's memory - never in
# terminal scrollback or shell history.
"$repo_dir/scripts/encrypt-env-files.sh" "$plaintext_file"

echo
echo "Pushing to GitHub secrets in every repo listed in scripts/actions-secrets.json:"
if ! "$repo_dir/scripts/sync-actions-secrets.mts"; then
  echo
  echo "Some secret push(es) failed - the new passwords are in ${plaintext_file}.encrypted;" >&2
  echo "retry with ./scripts/sync-actions-secrets.mts (add --repo/--secret to narrow it)." >&2
  exit 1
fi

cat <<'EOF'

Rotating means re-`docker login` everywhere the old passwords were used
that this script doesn't reach itself (CI runner pods, kind clusters, local
machines).
EOF
