resources:
  - ./namespace.yaml
  - ./helmrepositories
  - ./loki
  - ./alloy
  - ./prometheus
  - ./grafana
  - ./blackbox

namespace: monitoring

buildMetadata: [originAnnotations, transformerAnnotations]
