apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: beta-coinpoet-com-tls
  namespace: coinpoet-prod
spec:
  secretName: beta-coinpoet-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - beta.coinpoet.com
---
# Also create certificate for future coinpoet.com
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coinpoet-com-tls
  namespace: coinpoet-prod
spec:
  secretName: coinpoet-com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - coinpoet.com