apiVersion: v1
kind: PersistentVolume
metadata:
  name: coinpoet-prod-db-pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/thedatapool/app-data/coinpoet/prod/db-data
