apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 10m
  chart:
    spec:
      chart: wordpress
      version: "27.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 24h
  values:
    wordpressScheme: https

    ingress:
      enabled: false

    persistence:
      enabled: true

    mariadb:
      primary:
        persistence:
          enabled: true

    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
