apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wordpress
spec:
  interval: 10m
  chart:
    spec:
      chart: wordpress
      # Find latest version at https://app-catalog.vmware.com/bitnami/releases/a38d840c-0692-4786-87ec-e4eac1128259
      version: "29.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
      interval: 24h
  values:
    wordpressScheme: https

    ingress:
      enabled: false

    persistence:
      enabled: true

    mariadb:
      primary:
        persistence:
          enabled: true

    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "1"
        memory: "1Gi"
