apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - mariadb-pv-pvc.yaml
  - wordpress-pv-pvc.yaml

# https://github.com/bitnami/charts/tree/main/bitnami/wordpress
helmCharts:
- name: wordpress
  # NOTE: repo url found at https://docs.bitnami.com/kubernetes/get-started-gke/#step-5-install-an-application-using-a-helm-chart
  repo: https://charts.bitnami.com/bitnami
  version: 18.0.6
  valuesFile: ./chart-values.yaml

namespace: oksana-wordpress

buildMetadata: [originAnnotations, transformerAnnotations]

labels:
  - pairs:
      app.activescott.com/name: wordpress
      app.activescott.com/tenant: oksana

secretGenerator:
  - name: wordpress-user-creds
    envs:
    - .env.secret.wordpress-user-creds.encrypted
  - name: wordpress-mariadb-creds
    envs:
    - .env.secret.wordpress-mariadb-creds.encrypted
