apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml
  - mariadb-pv-pvc.yaml
  - wordpress-pv-pvc.yaml

namespace: oksana-wordpress

buildMetadata: [originAnnotations, transformerAnnotations]

labels:
  - pairs:
      app.activescott.com/name: wordpress
      app.activescott.com/tenant: oksana

secretGenerator:
  - name: wordpress-user-creds
    envs:
    - .env.secret.wordpress-user-creds.encrypted
  - name: wordpress-mariadb-creds
    envs:
    - .env.secret.wordpress-mariadb-creds.encrypted
