apiVersion: v1
kind: PersistentVolume
metadata:
  # NOTE: PersistentVolume resources are cluster-wide so we have to name these accordingly
  name: scott-willeke-com-logs-pv
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /mnt/thedatapool/app-data/scott-willeke-com/logs
  # NOTE: must set a PersistentVolume nodeAffinity when using local volumes
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ix-truenas