apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hoarder

secretGenerator:
  - envs:
      - .env.secret.hoarder-secrets.encrypted
    name: hoarder-secrets

configMapGenerator:
  - name: hoarder-configuration
    literals:
      - NEXTAUTH_URL=https://hoard.activescott.com

resources:
  - base/namespace.yaml
  - base/web-deployment.yaml
  - base/web-service.yaml
  - base/chrome-deployment.yaml
  - base/chrome-service.yaml
  - base/meilisearch-deployment.yaml
  - base/meilisearch-service.yaml
  - base/meilisearch-pvc.yaml
  - base/data-pvc.yaml
  - web-ingress.yaml
  - web-ingress-certificate.yaml
  - data-pv.yaml
  - meilisearch-pv.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: data-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data-pvc
      spec:
        volumeName: hoarder-data-pv
        storageClassName: ""
  - target:
      kind: PersistentVolumeClaim
      name: meilisearch-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: meilisearch-pvc
      spec:
        volumeName: hoarder-meilisearch-pv
        storageClassName: ""

  # change the web service from LoadBalancer -> ClusterIP:
  - target:
      kind: Service
      name: web
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: web
      spec:
        type: ClusterIP

images:
  - name: ghcr.io/hoarder-app/hoarder
    newName: ghcr.io/hoarder-app/hoarder
    newTag: 0.23.0
