apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hoarder

secretGenerator:
  - envs:
      - .env.secret.hoarder-secrets.encrypted
    name: hoarder-secrets

configMapGenerator:
  - name: hoarder-configuration
    literals:
      - NEXTAUTH_URL=https://hoard.activescott.com
      - DISABLE_SIGNUPS=true

resources:
  - base/namespace.yaml
  - base/web-deployment.yaml
  - base/web-service.yaml
  - base/chrome-deployment.yaml
  - base/chrome-service.yaml
  - base/meilisearch-deployment.yaml
  - base/meilisearch-service.yaml
  - base/meilisearch-pvc.yaml
  - base/data-pvc.yaml
  - web-ingress.yaml
  - web-ingress-certificate.yaml
  - data-pv.yaml
  - meilisearch-pv.yaml

patches:
  - target:
      kind: PersistentVolumeClaim
      name: data-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: data-pvc
      spec:
        volumeName: hoarder-data-pv
        storageClassName: ""
  - target:
      kind: PersistentVolumeClaim
      name: meilisearch-pvc
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: meilisearch-pvc
      spec:
        volumeName: hoarder-meilisearch-pv
        storageClassName: ""

  # change the web service from LoadBalancer -> ClusterIP:
  - target:
      kind: Service
      name: web
    patch: |-
      apiVersion: v1
      kind: Service
      metadata:
        name: web
      spec:
        type: ClusterIP

  # Add resource limits to chrome deployment:
  - target:
      kind: Deployment
      name: chrome
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: chrome
      spec:
        template:
          spec:
            containers:
            - name: chrome
              # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
              resources:
                limits:
                  cpu: "5"
                  memory: "0.5Gi"
                requests:
                  cpu: "0.5"
                  memory: "0.3Gi"

  # Add resource limits to meilisearch deployment:
  - target:
      kind: Deployment
      name: meilisearch
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: meilisearch
      spec:
        template:
          spec:
            containers:
            - name: meilisearch
              # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
              resources:
                limits:
                  cpu: "25"
                  memory: "1Gi"
                requests:
                  cpu: "0.5"
                  memory: "0.3Gi"

  # Add resource limits to web deployment:
  - target:
      kind: Deployment
      name: web
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: web
      spec:
        template:
          spec:
            containers:
            - name: web
              # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
              resources:
                limits:
                  cpu: "25"
                  memory: "2Gi"
                requests:
                  cpu: "0.5"
                  memory: "0.3Gi"

images:
  - name: ghcr.io/hoarder-app/hoarder
    newName: ghcr.io/hoarder-app/hoarder
    newTag: 0.27.1
