resources:
  - ./namespace.yaml
  - ./helmrepository.yaml
  - ./helmrelease.yaml

namespace: traefik

buildMetadata: [originAnnotations, transformerAnnotations]

commonLabels:
  # use `app.activescott.com/name` to avoid conflicts with other people's resources using "app" label.
  app.activescott.com/name: traefik
  app.activescott.com/tenant: everyone
