apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

patches:
  # patch flux controllers with prometheus scrape annotations per https://fluxcd.io/flux/monitoring/metrics/
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
        namespace: flux-system
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: "8080"
              prometheus.io/path: "/metrics"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
        namespace: flux-system
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: "8080"
              prometheus.io/path: "/metrics"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-controller
        namespace: flux-system
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: "8080"
              prometheus.io/path: "/metrics"
  - patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
        namespace: flux-system
      spec:
        template:
          metadata:
            annotations:
              prometheus.io/port: "8080"
              prometheus.io/path: "/metrics"
