apiVersion: v1
kind: PersistentVolume
metadata:
  name: fernfiles-prod-app-pv-data
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/thedatapool/app-data/fernfiles/prod/app-data
