scrape_configs:
  - job_name: "coinpoet_cache_metrics"
    # Standard scrape interval for good alerting responsiveness
    scrape_interval: 10s
    scrape_timeout: 10s
    metrics_path: "/ops/metrics"
    static_configs:
      - targets: ["coinpoet.com"]