apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: repo-browser-chaperone-slack-relay
  annotations:
    activescott.com/source-repo: activescott/browser-chaperone
spec:
  image: ghcr.io/activescott/browser-chaperone/slack-relay
  interval: 5h
  secretRef:
    name: github-container-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: policy-browser-chaperone-slack-relay
spec:
  imageRepositoryRef:
    name: repo-browser-chaperone-slack-relay
  policy:
    semver:
      range: ">=0.0.0"
