apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../../../../apps/production/shared/ghcr-pull-secret/
  - actions-runner.yaml
  - amazon-searcher.yaml
  - arc-controller.yaml
  - fernfiles-app.yaml
  - fernfiles-inference-service.yaml
  - fernfiles-worker.yaml
  - gpu-poet-collector.yaml
  - gpupoet-app.yaml
  - indexnow-notifier.yaml
  - olya.yaml
  - ramblefeed-app.yaml
  - scott-willeke-com.yaml
  - tinkerbell-app.yaml
  - tinkerbell-mcp-gateway.yaml

configurations:
  - secret-name-reference.yaml
