apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - ../ghcr-pull-secret/
  - amazon-searcher.yaml
  - dreamwright.yaml
  - browser-chaperone-app.yaml
  - browser-chaperone-browser.yaml
  - browser-chaperone-slack-relay.yaml
  - fernfiles-app.yaml
  - fernfiles-inference-service.yaml
  - fernfiles-worker.yaml
  - gpu-poet-collector.yaml
  - gpupoet-app.yaml
  - indexnow-notifier.yaml
  - job-accelerator-app.yaml
  - olya.yaml
  - ramblefeed-app.yaml
  - scott-willeke-com.yaml
  - tinkerbell-app.yaml
  - tinkerbell-mcp-gateway.yaml

configurations:
  - secret-name-reference.yaml
