apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: repo-olya
spec:
  image: ghcr.io/activescott/olya
  interval: 5h
  secretRef:
    name: github-container-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: policy-olya
spec:
  imageRepositoryRef:
    name: repo-olya
  filterTags:
    pattern: '^main-(?P<ts>[0-9]+)$'
    extract: '$ts'
  policy:
    numerical:
      order: asc
