apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: repo-scott-willeke-com
spec:
  image: ghcr.io/activescott/www
  interval: 5h
  secretRef:
    name: github-container-registry-secret
---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImagePolicy
metadata:
  name: policy-scott-willeke-com
spec:
  imageRepositoryRef:
    name: repo-scott-willeke-com
  filterTags:
    pattern: '^v[0-9]{12}$'
  policy:
    alphabetical:
      order: asc
