apiVersion: v1
kind: PersistentVolume
metadata:
  name: ramblefeed-prod-db-pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/thedatapool/app-data/ramblefeed/prod/db-data
