apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - stalwart-pv.yaml
  - stalwart-pvc.yaml
  - stalwart-certificate.yaml
  - stalwart-statefulset.yaml
  - stalwart-service.yaml
namespace: email-stalwart
secretGenerator:
  - name: stalwart-creds
    envs:
      - .env.secret.stalwart.encrypted
