apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-config
  namespace: email-stalwart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: email-stalwart-prod-pv-config
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data
  namespace: email-stalwart
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: email-stalwart-prod-pv-data
  resources:
    requests:
      storage: 50Gi
