# Reference:
# - https://cert-manager.io/docs/concepts/certificate/
# - https://cert-manager.io/docs/usage/certificate/
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sear-scott-willeke-com
spec:
  secretName: sear-scott-willeke-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: sear.scott.willeke.com
  dnsNames:
    - sear.scott.willeke.com
