resources:
  - namespace.yaml
  - ../../base/tayle/
  - app-ingress-certificate.yaml
  - rabbitmq-pv.yaml
  - db-pv.yaml

patches:
  - path: patch-app-ingress.yaml
  # patch the volume name of the PV's the PVC's used in the StatefulSets
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: tayle-prod-rabbitmq-pv-data
    target:
      kind: StatefulSet
      name: rabbitmq
  - patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/volumeName
        value: tayle-prod-db-pv-data
    target:
      kind: StatefulSet
      name: db

namespace: tayle-prod

# PV's are not in a namespace and since they come from a common base, we have to prefix or suffix their name: https://github.com/kubernetes-sigs/kustomize/issues/4832#issuecomment-1344574518
nameSuffix: tayle-prod

secretGenerator:
  # db
  - name: db-creds
    envs:
      - .env.secret.db.encrypted
  # rabbit
  - name: rabbitmq-creds
    envs:
      - .env.secret.rabbitmq.encrypted
  # app
  - name: app-creds
    envs:
      - .env.secret.app.encrypted
  # worker:
  - name: worker-creds
    envs:
      - .env.secret.worker.encrypted
  # image pull secret:
  - name: ghcr-auth
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=ghcr.dockeronfigjson.encrypted

# https://kubectl.docs.kubernetes.io/references/kustomize/builtins/#_imagetagtransformer_
images:
  - name: tayle-image-app
    newName: ghcr.io/activescott/tayle/app
    newTag: main-85548a2 # replace this tag to update app
  - name: tayle-image-worker
    newName: ghcr.io/activescott/tayle/worker
    newTag: main-85548a2 # replace this tag to update worker
  - name: tayle-image-db
    newName: postgres
    newTag: "17"
  - name: tayle-image-rabbitmq
    newName: rabbitmq
    newTag: 3-management
