apiVersion: v1
kind: PersistentVolume
metadata:
  name: zot-registryk8s-storage-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/thedatapool/no-backup/app-data/zot-registryk8s
    type: DirectoryOrCreate
  claimRef:
    name: zot-registryk8s-storage-pvc
    namespace: zot-oci-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-registryk8s-storage-pvc
  namespace: zot-oci-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
  volumeName: zot-registryk8s-storage-pv
