apiVersion: v1
kind: PersistentVolume
metadata:
  name: zot-ghcr-storage-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/thedatapool/no-backup/app-data/zot-ghcr
    type: DirectoryOrCreate
  claimRef:
    name: zot-ghcr-storage-pvc
    namespace: zot-oci-registry
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zot-ghcr-storage-pvc
  namespace: zot-oci-registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: zot-ghcr-storage-pv
