apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/image-scanning/semver

configurations:
  - secret-name-reference.yaml

patches:
  # Customize ImageRepository
  - target:
      kind: ImageRepository
      name: repo-placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: repo-fernfiles-app
      - op: replace
        path: /spec/image
        value: ghcr.io/activescott/fernfiles/app

  # Customize ImagePolicy
  - target:
      kind: ImagePolicy
      name: policy-placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: policy-fernfiles-app
      - op: replace
        path: /spec/imageRepositoryRef/name
        value: repo-fernfiles-app

  # Customize ImageUpdateAutomation
  - target:
      kind: ImageUpdateAutomation
      name: update-placeholder
    patch: |-
      - op: replace
        path: /metadata/name
        value: update-fernfiles-app
