apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb-data
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-mariadb-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb-initdb
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-mariadb-initdb-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-wp-content
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-wp-content-pv
