apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb-data-202609
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-202609-mariadb-data-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-mariadb-initdb-202609
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-202609-mariadb-initdb-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-wp-content-202609
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: wordpress-micah-mmm-v2-202609-wp-content-pv
