resources:
  - ./namespace.yaml
  - ../../base/transmission

buildMetadata: [originAnnotations, transformerAnnotations]

namespace: transmission

secretGenerator:
  - name: transmission-creds
    envs:
      - .env.secret.transmission.encrypted
