apiVersion: v1
kind: PersistentVolume
metadata:
  name: gpu-poet-collector-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /mnt/thedatapool/app-data/gpu-poet-collector/prod/data
