apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gpu-poet-collector-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
  volumeName: gpu-poet-collector-pv
