apiVersion: v1
kind: Service
metadata:
  name: gpu-poet-collector
  labels:
    app: gpu-poet-collector
spec:
  selector:
    app: gpu-poet-collector
  ports:
    - name: metrics
      port: 9100
      targetPort: 9100
  type: ClusterIP
