resources:
  - namespace.yaml
  - ../../base/wordpress
  - pv.yaml

secretGenerator:
  - name: wordpress-creds
    options:
      disableNameSuffixHash: true
    envs:
      - .env.secret.wordpress-creds.encrypted

patches:
  - path: patch-helmrelease.yaml

namespace: wordpress-micah-mmm
