resources:
  - ./certificate.yaml
  - ./prometheus-ingress.yaml
  - ./prometheus-pv.yaml
  - ./helmrelease.yaml
  - ./basic-auth-middleware.yaml

secretGenerator:
  - name: alertmanager-secrets
    options:
      disableNameSuffixHash: true
    envs:
      - .env.secret.alertmanager.encrypted
  - name: prometheus-basic-auth
    options:
      disableNameSuffixHash: true
    files:
      - users=basic-auth-users

labels:
  - pairs:
      app.activescott.com/name: prometheus
