resources:
  - https://raw.githubusercontent.com/kubernetes/kube-state-metrics/refs/tags/v2.15.0/examples/standard/service.yaml

patches:
  - patch: |
      apiVersion: v1
      kind: Service
      metadata:
        name: kube-state-metrics
        namespace: kube-system

        # add the prometheus scrape annotations:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "8080"
          prometheus.io/path: "/metrics"
