apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/db-backup

images:
  - name: db-backup-image-placeholder
    newName: postgres
    newTag: "18@sha256:4ef4dbc939d61acea57712655ddb4b4ab27419c913f94cca0cd57cb3ea3c2280"

patches:
  - target:
      kind: PersistentVolumeClaim
      name: db-backup-pvc
    patch: |-
      - op: replace
        path: /spec/volumeName
        value: tayle-prod-db-backup-pv
