apiVersion: batch/v1
kind: CronJob
metadata:
  name: cache-revalidation
spec:
  # We get 5,000 API calls per day in eBay's call limits per
  # https://developer.ebay.com/develop/get-started/api-call-limits. 
  # In some extreme circumstances I've seen it use ~1,000 API calls per run (5 runs per day). 
  # However, under normal circumstances it seems to use ~230 calls.
  # So 6 runs (every 4 hrs) should be plenty conservative.
  schedule: "0 /4 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: cache-revalidation
              # Use lightweight curl image for simple HTTP requests
              image: curlimages/curl:latest
              command:
                - /bin/sh
                - -c
                - |
                  echo "Starting cache revalidation job..."

                  # Call the internal revalidate-cache endpoint
                  if curl -f -X POST -w "Status: %{http_code}\n" http://app:3000/ops/revalidate-cache; then
                    echo "Cache revalidation completed successfully"
                  else
                    echo "Cache revalidation failed"
                    exit 1
                  fi

              # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
              resources:
                limits:
                  cpu: "0.1"
                  memory: "100Mi"
                requests:
                  cpu: "0.05"
                  memory: "50Mi"
