apiVersion: batch/v1
kind: CronJob
metadata:
  name: indexnow-notifier
spec:
  # Run every 4 hours
  schedule: "0 */4 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: indexnow-notifier
              image: indexnow-notifier-image-placeholder
              env:
                - name: INDEXNOW_API_KEY
                  valueFrom:
                    secretKeyRef:
                      name: app-creds
                      key: INDEXNOW_API_KEY
                - name: SITEMAP_URL
                  value: "https://gpupoet.com/sitemap.xml"
                - name: HOST
                  value: "gpupoet.com"
                - name: STATE_DIR
                  value: "/data/pages"
              resources:
                limits:
                  cpu: "0.1"
                  memory: "100Mi"
                requests:
                  cpu: "0.05"
                  memory: "50Mi"
              volumeMounts:
                - name: indexnow-storage
                  mountPath: /data
          volumes:
            - name: indexnow-storage
              persistentVolumeClaim:
                claimName: indexnow-pvc
