apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-storage-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/thedatapool/no-backup/app-data/loki
    type: DirectoryOrCreate
  claimRef:
    name: loki-storage-pvc
    namespace: monitoring
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-storage-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 50Gi
  volumeName: loki-storage-pv
