apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./namespace-arc-systems.yaml
  - ./namespace-arc-runners.yaml
  - ./helmrepositories
  - ./controller
  - ./runners/tinkerbell
  - ./runners/ramblefeed
  - ./runners/fernfiles
  - ./runners/job-accelerator
  - ./runners/home-infra-k8s-flux
  - ./runners/auth
  - ./runners/activeassistant
  - ./runners/gpu-agent
  - ./runners/browser-chaperone

buildMetadata: [originAnnotations, transformerAnnotations]
