apiVersion: v1
kind: Service
metadata:
  name: olya-egress-proxy
  namespace: browser-chaperone-prod
spec:
  selector:
    app: olya-egress-proxy
  ports:
    - name: proxy
      port: 3128
      targetPort: 3128
      protocol: TCP
