- op: add
  path: /spec/template/spec/imagePullSecrets
  value:
    - name: github-container-registry-secret
- op: add
  path: /spec/template/spec/containers/0/envFrom/-
  value:
    secretRef:
      name: internal-api-token
